import Head from 'next/head'
import Link from 'next/link'

import { useEffect, useState } from 'react'

import { ChakraProvider, CircularProgress, CircularProgressLabel } from "@chakra-ui/react"

function About() {

    const [progress, setProgress] = useState(0)

    useEffect(() => {

        const interval = setTimeout(() => {

            if(progress < 100) setProgress(progress + 10)
            else setProgress(0)

        }, 500)

        return () => clearInterval(interval)

    })

    return (
        <div>
            <Head>
                <title>About - Next</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <ChakraProvider>
                <CircularProgress size="120px" value={progress} color="green.400"> 
                    <CircularProgressLabel>{progress}%</CircularProgressLabel>
                </CircularProgress>
            </ChakraProvider>

            <Link href="/">
                <a>Home</a>
            </Link>
        </div>
    )
}

export default About