import Head from 'next/head'
import Link from 'next/link'

function Dashboard() {

    return (
        <div>
            <Head>
                <title>About - Next</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>

                <h1>Dashboard</h1>
            
                <Link href="/about">
                    <a>About</a>
                </Link>
            </main>

        </div>
    )
}

export default Dashboard